name: master

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes

jobs:
  call-workflow:
    name: "Publish nuget matrix (master)"
    uses: dannoe/ALC-analyzer-dlls/.github/workflows/publish_nuget_matrix.yml@master
    with:
      NUGET_SOURCE: ${{ vars.NUGET_SOURCE }}

    secrets:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
