name: test

on:
  push:
    branches:
      - test
jobs:
  call-workflow:
    name: "Publish nuget matrix (test)"
    uses: dannoe/ALC-analyzer-dlls/.github/workflows/publish_nuget_matrix.yml@test
    with:
      NUGET_SOURCE: ${{ vars.NUGET_STAGING_SOURCE }}

    secrets:
      NUGET_APIKEY: ${{ secrets.NUGET_STAGING_APIKEY }}
